name: "fix-dubious-ownership-action"
description: "fix-dubious-ownership-action"

inputs:
  github_repo_name:
    description: "GitHub repository name"
    default: ${{ github.event.repository.name }}

runs:
  using: "composite"
  steps:
    - name: Fix dubious ownership
      shell: bash
      run: |
        git config --global --add safe.directory .
        git config --global --add safe.directory "/__w/${REPOSITORY_NAME}/${REPOSITORY_NAME}"
      env:
        REPOSITORY_NAME: ${{ inputs.github_repo_name }}

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: "message-square"
  color: "gray-dark"
